electric-cloud/EC-Docker

- dsl/procedures/createConfiguration/form.xml
Modified tooltips for various certificates on create configuration page.
> [ECPDOCKER-4] Modified tooltips

- dsl/procedures/createConfiguration/form.xml
Changed label of Docker Host parameter and made 'Test Connection' optional parameter on 'Create Configuration' page.
> [ECPDOCKER-5] Label updates

- dsl/properties/scripts/DockerClient.groovy
Added support for deploying single container on standalone docker engine. The procedure will work for both windows and linux platform.
> [ECPDOCKER-12] Support for container deploy on standalone docker engine

- dsl/properties/scripts/DockerClient.groovy
Added support for Volumes and Mem/CPU limits/reservations.
> Added support for volumes for container deployment.

- .gitignore
- META-INF/project.xml
- dev/build.sh
- dsl/procedures/createConfiguration/procedure.dsl
- dsl/procedures/defineContainer/containerMappingsForm.xml
- dsl/procedures/defineContainer/form.xml
- dsl/procedures/defineContainer/procedure.dsl
- dsl/procedures/defineContainer/steps/generateSpec.groovy
- dsl/procedures/defineService/form.xml
- dsl/procedures/defineService/procedure.dsl
- dsl/procedures/defineService/serviceMappingsForm.xml
- dsl/procedures/defineService/steps/generateSpec.groovy
- dsl/procedures/setup/steps/retrieveGrapeDependencies.pl
- dsl/promote.groovy
- pages/help.xml
ECPDOCKER-18
Added service and container mapping parameters back
Removed Kubernetes references
> service and container mapping parameters

- pages/help.xml
Added steps to generate TLS client side certificates in help page.
> [ECPDOCKER-15] Steps for TLS cert generation for docker stand-alone

- dsl/properties/scripts/DockerClient.groovy
Added support for serviceNameOverride from service mapping if supplied by user.
> [ECPDOCKER-22] Support for serviceNameOverride 

- dsl/properties/scripts/DockerClient.groovy
Fixed volume support for docker standalone mode.
> [ECPDOCKER-37] Volume support for docker standalone mode.

- dsl/properties/scripts/DockerClient.groovy
Since Docker Container [API](https://docs.docker.com/engine/api/v1.29/#operation/ContainerUpdate) only supports update of hostConfig params, out of which only 4 are supported by us in FlowUI.
So, the plugin will update only below input parameters:
1. Minimum CPU requested
2. Maximum CPU allowed
3. MemoryMemory
4. Limit
> [ECPDOCKER-20] Update container on standalone docker engine.

- dsl/properties/scripts/DockerClient.groovy
Added support for both Docker volumes and bind(hostPath) for docker swarm services.
In case of Docker volumes, user have to create a volume first manually and then can mention volume name in volume input param of Flow Service.
```
[{ 
"name": "web-content", 
"hostPath": ""  
}] 
```
hostPath needs to be empty here.
In Flow Container, user can mention the mount path where the volume needs to be mounted.
```
[{ 
"name": "web-content", 
"mountPath": "/usr/share/nginx/html"
}]
```
> Support for bind(hostPath) and Docker volumes for Swarm services

- dsl/properties/scripts/EFClient.groovy
PR to convert docker compose v3 file to ElectricFlow MicroServices model.
> Discover Feature [WIP]

- dsl/properties/scripts/EFClient.groovy
Added support for CPU/Memory limits and reservations and update parallelism from Docker compose file.
> Discover Feature

- dsl/procedures/defineService/form.xml
- dsl/procedures/defineService/serviceMappingsForm.xml
- dsl/properties/scripts/DockerClient.groovy
- pages/help.xml
Added multiple network support (with subnets and gateways) for docker standalone and swarm.
> [ECPDOCKER-50] MultiNetwork Support 

- dsl/procedures/createIngress/form.xml
- dsl/procedures/createIngress/procedure.dsl
- dsl/procedures/createIngress/steps/createIngress.groovy
- dsl/procedures/deleteNetwork/form.xml
- dsl/procedures/deleteNetwork/procedure.dsl
- dsl/procedures/deleteNetwork/steps/deleteNetwork.groovy
- dsl/promote.groovy
- dsl/properties/scripts/DockerClient.groovy
- pages/help.xml
Added support for creating Ingress network and to delete a network.
> [ECPDOCKER-50] Added "Create Ingress" and "Delete Network" procedures

- dsl/procedures/discover/steps/discover.groovy
Fixed the condition for 'Recreate Application' parameter for "Discover" procedure.
> [ECPDOCKER-52] Discover Procedure

- dsl/properties/scripts/DockerClient.groovy
Store exposed service URL:Port in property sheet.
> [ECPDOCKER-54] Added endpoint-saving functionality.

- dsl/properties/scripts/DockerClient.groovy
Added attachAdditionalNetworks() call in container update procedure. If new network is added in networkList during update, it will get created and attached.
> [ECPDOCKER-53] Attach additional networks in container update

- dsl/properties/scripts/DockerClient.groovy
To support updateContainer case on standalone docker engine, delete the container if it is already deployed.
> [ECPDOCKER-20] Update container on standalone docker engine

- dsl/procedures/deployService/steps/createOrUpdateDeployment.groovy
- dsl/promote.groovy
- dsl/properties/scripts/BaseClient.groovy
- dsl/properties/scripts/DockerClient.groovy
- dsl/properties/scripts/EFClient.groovy
- dsl/properties/scripts/Logger.groovy
o Registered 'undeployService' properties for the plugin
o Cleaned up the undeploy logic for stand-alone docker instance - using 'inspect' API instead of 'ps' to find the container by name to ensure an exact match. 'ps' matches all containers whose name contains the specified value.
o Logs cleanup
> Registered 'Undeploy Service' procedure as 'undeployService' operation

- dsl/procedures/defineService/serviceMappingsForm.xml
- pages/help.xml
> [ECPDOCKER-60] Modify tooltip and documentation for docker network

- ec_setup.pl
This reverts commit 2a9e449f9314f491573acf3018619dfb2d855430.
> Revert "Updated ec_setup.pl to allow remote installation via ectool"

- dsl/properties/scripts/EFClient.groovy
- dsl/properties/scripts/ImportMicroservices.groovy
o Created links/report urls for the application created (for application scoped services) or for the top-level services created  for the 'Import Microservices' procedure.
o Added service discovery details to the job step summary in addition to the existing job summary.
o Replaced the image path parsing logic with similar logic from EC-Kubernetes for consistency. Also fixed an issue with registry getting prefixed with image name.
> Create app and services links

- dsl/procedures/importMicroservices/steps/importMicroservices.groovy
- dsl/properties/scripts/ImportMicroservices.groovy
ECPDOCKER-116: Fixed duplicate process exception
> A bit of cleanup

- dsl/properties/scripts/ImportMicroservices.groovy
The results of networks' investigation.
> Brief fix for multiple networks logic

- dsl/properties/scripts/ImportMicroservices.groovy
Reverts electric-cloud/EC-Docker#103 - Had merged this PR by mistake.
> Revert "Brief fix for multiple networks logic"

- META-INF/plugin.xml
- dev/build.sh
- dsl/procedures/createConfiguration/steps/createAndAttachCredential.pl
- dsl/procedures/deleteConfiguration/steps/deleteConfiguration.pl
- pages/help.xml
Configurations can be created by users with "@" sign in a name.
> ECPLUGINS-15

- config/pluginspec.yaml
- help/changelog.yaml
- help/metadata.yaml
This PR updates the pluginspec.yaml, changelog.yaml, and metadata.yaml files with copy edits for the documentation automation.
> [DOCS-6126] Copy edits for the Docker plugin documentation

- specs/src/test/groovy/com/cloudbees/pdk/hen/tests/RunDockerBuildSuite.groovy
- specs/src/test/groovy/com/cloudbees/pdk/hen/tests/RunDockerPullSuite.groovy
- specs/src/test/groovy/com/cloudbees/pdk/hen/tests/RunDockerRunSuite.groovy
**What does this PR do?**
- Added negative test cases for RunDockerBuild, RunDockerPull and RunDockerRun procedures.
Note: these procedures do not fill Summary, that is reason I am not asserting it.
> Automation coverage improvement

- specs/src/test/groovy/com/cloudbees/pdk/hen/tests/RunDockerRunSuite.groovy
Fixed a spec test failure issue.
> CDRO-920 - Fixed a spec test failure issue.
